<?php

namespace Faculte\AdminBundle\Repository;

/**
 * AbsenceEtdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceEtdRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByGroupeAndMatiere($idMatiere,$idGroupe){
        $query = $this->createQueryBuilder('ab_etd')
            ->select('ab_etd')
            ->leftJoin('ab_etd.matiere', 'matiere')
            ->leftJoin('ab_etd.etudiant', 'etd')
            ->leftJoin('etd.groupe', 'groupe')
            ->where('groupe.id = :IdGroupe')
            ->andWhere('matiere.id = :IdMatiere')
            ->setParameters(array('IdGroupe'=>$idGroupe,'IdMatiere'=>$idMatiere))
            ->getQuery()
            ->getResult();
        return $query;
    }

    public function findByEtdAndMatiere($idMatiere,$idEtd){
        $query = $this->createQueryBuilder('ab_etd')
            ->select('ab_etd')
            ->leftJoin('ab_etd.matiere', 'matiere')
            ->leftJoin('ab_etd.etudiant', 'etd')
            ->where('matiere.id = :idMatiere')
            ->andWhere('etd.id = :idEtd')
            ->setParameters(array('idEtd'=>$idEtd,'idMatiere'=>$idMatiere))
            ->getQuery()
            ->getOneOrNullResult();
        return $query;
    }
}
