<?php

namespace Faculte\AdminBundle\Repository;

/**
 * PublierDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublierDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
