<?php

namespace Faculte\AdminBundle\Repository;

/**
 * PublierFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublierFileRepository extends \Doctrine\ORM\EntityRepository
{
}
