<?php

namespace Faculte\AdminBundle\Repository;

/**
 * PublierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublierRepository extends \Doctrine\ORM\EntityRepository
{
}
