<?php

namespace Faculte\AdminBundle\Repository;

/**
 * PublierImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublierImageRepository extends \Doctrine\ORM\EntityRepository
{
}
